[unstable]
build-std = ["core", "std", "alloc", "proc_macro", "panic_abort"]
build-std-features = ["default", "optimize_for_size"]

[build]
rustflags = [
    "-Z", "threads=8",
    "-C", "embed-bitcode=no",
]
